log2console: true
manifest: "loader-manifest.yaml"

# Golang date formation
#    year: 2006
#   month: 01
#     day: 02
#   hours: 15
# minutes: 04
# seconds: 05
logging:
  script: "script_log/loader-logs_{200601021504}.log"
  files: "script_log/loader-files_{200601021504}.log"

# Loader modes:
#  compress
#  cleaner
## Archive algorithm:
##  gzip
##  zip
services:
- name: "delete"
  mode: cleaner
  sourceFolder: "/local/logs"
  # destinationFolder: "./dst"
  filePrefix: "file-"
  fileExtension: "txt"
  maxTime: 1
  windowLimit: 1

- name: "archive"
  mode: compress
  sourceFolder: "/local/logs"
  destinationFolder: "/local/logs/archive"
  filePrefix: "file-"
  fileExtension: "txt"
  archive: "gzip"
  maxTime: 2
  windowLimit: 1
